version: '2'

volumes:
  fabric-protos:

services:

  fabric-protos:
    image: tittuvarghese/fabric-protos-baseos
    command: sh -c './generate.sh'
    volumes:
      - ../organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
    container_name: ca_org1
